name: Tests

on:
  pull_request:

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    # See: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#using-the-checkout-action
    - uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/hydrogen'
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run build
